services:
  mysql:
    image: 'mysql:latest'
    container_name: animal_hospital_db
    environment:
      MYSQL_DATABASE: ${name}
      MYSQL_USER: ${username}
      MYSQL_PASSWORD: ${password}
      MYSQL_ROOT_PASSWORD: ${root_password}
    ports:
      - '3306'

    volumes:
      - ./src/main/resources/schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - ./src/main/resources/private.sql:/docker-entrypoint-initdb.d/private.sql

  app:
    build: .
    container_name: animal_hospital_app