services:
  app:
    build: .
    container_name: animal_hospital_app
    ports:
      - "8080:8080"
    env_file:
      - /home/ubuntu/app/.env
    environment:
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
      SPRING_DATASOURCE_URL: ${db_url}
      SPRING_DATASOURCE_USERNAME: ${username}
      SPRING_DATASOURCE_PASSWORD: ${password}
    depends_on:
      - redis

  redis:
    image: redis:7
    container_name: animal_hospital_redis
    ports:
      - "16379:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data:
