spring:
  application:
    name: animal_Hospital_Service

  session:
    redis:
      namespace: spring:session

  jpa:
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
      hibernate.jdbc.batch_size: 1000
      hibernate.order_inserts: true
      hibernate.order_updates: true
      hibernate.ddl-auto: update

  data:
    redis:
      host: localhost
      port: 6379


  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    name: "animal_hospital_db"
    username: ${username}
    password: ${password}
    url: "jdbc:mysql://localhost:3306/animal_hospital_db?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC"
    #mysql:3306

server:
  servlet:
    session:
      cookie:
        name: JSESSIONID
#
#
#
#
#logging:
#  level:
#    MJ:
#      animal_Hospital_Service: DEBUG
#    org:
#      springframework:
#        web:
#          nodeValue: DEBUG
#          client:
#            RestTemplate: DEBUG
