spring:
  application:
    name: animal_Hospital_Service

  jpa:
    properties:
      hibernate.jdbc.batch_size: 1000
      hibernate.order_inserts: true
      hibernate.order_updates: true



  data:
    redis:
      host: localhost
      port: 6379
